test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# VAMOS USAR AWS EM PROD

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: 'AKIA3377WCNZARF5U66O'
  secret_access_key: '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'
  region: us-east-1
  bucket: photosher